mode = "nightly"

[client]
dns_threads = 4
bitcoin_rpc_url = "http://localhost:18332"
bitcoin_rpc_user = "xyz"
bitcoin_rpc_password = "xyz"
infura_key = "16a351590d9946989cdc80712e74f25e"
infura_secret = "b18f14aa53094950a51597600e41c422"
stq_contract_address = "0x1bf2092a42166b2ae19b7b23752e7d2dab5ba91a"
stq_transfer_topic = "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"
stq_approval_topic = "0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925"

[poller]
bitcoin_interval_secs = 60
bitcoin_number_of_tracked_confirmations = 4
ethereum_interval_secs = 10
ethereum_number_of_tracked_confirmations = 18
storiqa_interval_secs = 10
storiqa_number_of_tracked_confirmations = 18


[rabbit]
url = "amqp://guest:guest@localhost:5672//?heartbeat=3&frame_max=131072"
thread_pool_size = 2
connection_timeout_secs = 10
connection_pool_size = 10
