mode = "nightly"

[server]
host = "0.0.0.0"
port = 8000

[client]
dns_threads = 4
blockcypher_token = "5979b604fb114080b5761dba871009c0"
infura_key = "16a351590d9946989cdc80712e74f25e"
infura_secret = "b18f14aa53094950a51597600e41c422"

[poller]
bitcoin_interval_secs = 60
ethereum_interval_secs = 10

[rabbit]
url = "amqp://guest:guest@localhost:5672/vhost?heartbeat=15&frame_max=131072"
thread_pool_size = 2
connection_timeout_secs = 10
connection_pool_size = 10
